language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true   NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-convex-decomposition ros-hydro-ivcon"
  - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false  NOT_TEST_INSTALL=true EXTRA_DEB="ros-hydro-convex-decomposition ros-hydro-ivcon"
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true   NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false  NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"
matrix:
  allow_failures:
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true   NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"
  - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false  NOT_TEST_INSTALL=true EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
