# http://wiki.ros.org/viso2_ros

# tf related
odom_frame_id: /odom
base_link_frame_id: /car_center
publish_tf: false
sensor_frame_id: /left_camera_optical_frame

# Bucketing parameters
max_features: 2
bucket_width: 50.0
bucket_height: 50.0

# Matcher parameters
nms_n: 3
nms_tau: 50
match_binsize: 50
match_radius: 200
match_disp_tolerance: 2
outlier_disp_tolerance: 5
outlier_flow_tolerance: 5
multi_stage: 1
half_resolution: 1
refinement: 1

# stereo odometer parameters
queue_size: 5
approximate_sync: true  # false
ransac_iters: 200
inlier_threshold: 1.5
reweighting: true
ref_frame_change_method: 0
ref_frame_motion_threshold: 5.0
ref_frame_inlier_threshold: 150