- direction: 'horizontal'
- name: 'valve edge grasp'
  service: 'valve_edge_grasp'
  image: "package://drc_task_common/icons/valve-edge.png"
  image_size: [80, 80]
  column: 0
- name: 'valve center grasp'
  service: 'valve_center_grasp'
  image: "package://drc_task_common/icons/valve-center.png"
  image_size: [80, 80]
  column: 0
- name: 'drill normal grasp'
  service: 'drill_normal_grasp'
  image: "package://drc_task_common/icons/wall-icon.png"
  image_size: [80, 80]
  column: 1
- name: 'drill reverse grasp'
  service: 'drill_reverse_grasp'
  image: "package://drc_task_common/icons/wall-icon.png"
  image_size: [80, 80]
  column: 1
