- direction: 'horizontal'
- name: 'larm only'
  service: 'larm_only_checked'
  image: "package://drc_task_common/icons/left-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'larm preferred'
  service: 'larm_preferred_checked'
  image: "package://drc_task_common/icons/auto-left-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'rarm preferred'
  service: 'rarm_preferred_checked'
  image: "package://drc_task_common/icons/auto-right-hand-icon.png"
  image_size: [150, 100]
  column: 0
  default_value: True
- name: 'rarm only'
  service: 'rarm_only_checked'
  image: "package://drc_task_common/icons/right-hand-icon.png"
  image_size: [150, 100]
  column: 0
- name: 'enable-head-overwrite'
  service: 'enable_head_overwrite'
  image: "package://drc_task_common/icons/enable-head-overwrite.png"
  image_size: [100, 100]
  column: 1
- name: 'disable-head-overwrite'
  service: 'disable_head_overwrite'
  image: "package://drc_task_common/icons/disable-head-overwrite.png"
  image_size: [100, 100]
  column: 1

