- name: "robot"
  frame-id: "/robot_marker_root"
  robot: false
  mode: "visualization"
  # mode: "registration"
  model_param: "robot_urdf"
  scale: 1.0
  pose: 
    position: 
        x: 0.0
        y: 0.0
        z: 0.0
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  offset: 
    position:
        x: 0.035589
        y: 0.01
        z: -0.105
    orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  fixed_link:
    - "LLEG_LINK5"
    - "RLEG_LINK5"
  display: true
